# Analise Multivariada. Análise de Coordenadas Principais (PCO). 
# analisar distribuicao de plantas invasoras no cultivo de milho. 

 # Análise de Coordenadas Principais (PCoA ou Escala multidimensional, MDS) é um 
# método para explorar e visualizar semelhanças ou dissimilaridades de dados. 
# Começa com uma matriz de similaridade ou matriz de dissimilaridade (= matriz de distância) 
# e atribui a cada item uma localização em um espaço de baixa dimensão, 
# por exemplo, como um gráfico 3D.

# O PCoA é conceitualmente semelhante ao PCA e à análise de correspondência (CA), 
# que preservam as distâncias Eudliciana e qui-quadrada entre os objetos, respectivamente; 
# no entanto, o PCoA pode preservar as distâncias geradas a partir de qualquer 
# medida de (des) similaridade, permitindo um tratamento mais flexível de dados 
# ecológicos complexos. PCA é comumente usado para semelhanças e PCoA para dissimilaridades.

### pacotes 
# install.packages('Rtools') 
# install.packages('magrittr') 
# install.packages('tidyverse') 
library(magrittr)
library(tidyverse)
# library(FactoMineR)
# library(factoextra)

### dados 
planilha <- read.csv('dadosPCAcomMilho.csv', sep=';', dec=',' , header = TRUE, stringsAsFactors=F)
#planilha <- read.csv('dadosPCAsemMilho.csv', sep=';', dec=',' , header = TRUE, stringsAsFactors=F)
tabela <- planilha %>% select(-Zema)

head(planilha)
head(tabela)

### Distancia
# A função dist() calcula uma matriz de distância de um quadro de dados de objetos por variáveis usando uma de suas métricas de distância embutidas (mais sobre isso abaixo).
# The dist() function calculates a distance matrix from a data frame of objects by variables using one of its inbuilt distance metrics (more on this below).
campo.distancia <- dist(tabela, method = "euclidean", diag=TRUE)

### Analise de PCO
# Escalonamento multidimensional clássico (MDS) de uma matriz de dados. Também conhecida como análise de coordenadas principais (Gower, 1966).
#
# Classical multidimensional scaling (MDS) of a data matrix. Also known as principal coordinates analysis (Gower, 1966).
# The cmdscale() function then takes the distance matrix generated by dist() and performs a classical PCO. Then, as with nearly all multivariate methods, the output from the PCO needs to be examined in graph form to interpret the result of the analysis.

campo.pco <- cmdscale(campo.distancia, eig = TRUE, k = 11, x.ret = TRUE)

eig_num <- seq(1, length(campo.pco$eig), 1)
eig_num <- tabela$tratamento

barplot(campo.pco$eig, names.arg = eig_num, legend.text = TRUE, main = "Gráfico de autovalor de PCO")

campo.pco.dim1 <- vector(length = 54)
campo.pco.dim2 <- vector(length = 54)
campo.pco.dim3 <- vector(length = 54)
campo.pco.dim1 <- campo.pco$points[, 1]
campo.pco.dim2 <- campo.pco$points[, 2]
campo.pco.dim3 <- campo.pco$points[, 3]

# Plot Dim 1 e Dim 2
campo.pco.plot <- plot(campo.pco.dim1, campo.pco.dim2,
                       asp = 1, cex = 4,
                       xlab = "PCO dim 1", ylab = "PCO dim 2")

text(campo.pco.dim1, campo.pco.dim2, cex = 0.7, tabela$tratamento)

# Plot Dim 1 e Dim 3
campo.pco.plot <- plot(campo.pco.dim1, campo.pco.dim3,
                       asp = 1, cex = 4,
                       xlab = "PCO dim 1", ylab = "PCO dim 3")

text(campo.pco.dim1, campo.pco.dim3, cex = 0.7, tabela$tratamento)

# Plot Dim 2 e Dim 3
campo.pco.plot <- plot(campo.pco.dim2, campo.pco.dim3,
                       asp = 1, cex = 4,
                       xlab = "PCO dim 2", ylab = "PCO dim 3")

text(campo.pco.dim2, campo.pco.dim3, cex = 0.7, tabela$tratamento)


### OLD
# Model FactoMiner 

#res_pca <- PCA(data.matrix(planilha) %>% select(-Arab), quali.sup = 1, graph = FALSE)
res_pca <- PCA(tabela, quali.sup = 1, graph = FALSE)
summary(res_pca)
sweep(res_pca$var$coord, 2, sqrt(res_pca$eig[1:ncol(res_pca$var$coord),1]), FUN = '/')

###### usando baseR 
data.matrix(tabela) %>% prcomp()
data.matrix(tabela) %>% princomp()

# Grafico variacao 
fviz_contrib(res_pca, choice = "var", axes = c(1,2))
fviz_contrib(res_pca, choice = "var", addlabels=T, ylim=c(0,30))

##############
# visualizacao 
##############
fviz_pca_biplot(res_pca) 

fviz_pca_biplot(res_pca, col.var = "blue", geom.ind = "point", repel = "true", pointshape = 24, pointsize = 3 , fill.ind = tabela$tratamento)+
    theme_minimal() +
    labs(title="Analise Multivariada", fill="Tratamentos")

#teste
Tratamento = tabela$tratamento

fviz_pca_biplot(res_pca, col.var = "blue", repel = TRUE) +
    geom_point(aes(shape=Tratamento, color=Tratamento), size=7) + 
    scale_shape_manual(values=c(0,7,15, 1,13,19, 5,9,18, 2,14,17))+
    theme_classic() +
    labs(title="Analise Multivariada", fill="Tratamentos")


##############
# formato circular 
fviz_pca_var(res_pca, col.var = "blue")

fviz_pca_var(res_pca, col.var = "blue", geom.ind = "point", pointshape = 21, pointsize = 3 , fill.ind = tabela$tratamento)+
    theme_classic() +
    labs(title="Analise Multivariada", fill="Tratamentos",
    x="PCA1", y="PCA2")


### Referências 
# 
# ANÁLISE DE COMPONENTES PRINCIPAIS (PCA): CÁLCULO E APLICAÇÃO NO R. Disponível em https://operdata.com.br/blog/analise-de-componentes-principais-pca-calculo-e-aplicacao-no-r/. Acesso em 13 out. 2021. 
#
# Principal Coordinates Analysis. disponível em https://openplantpathology.github.io/OPP_Workshop_Multivariate/2-MV_PCO.html. Acesso em 13 out. 2021. 