# Analise Multivariada. Análise de Componentes Principais (PCA). 

# -----------
### pacotes 
# -----------
if(!require('pacman')) {
  install.packages('pacman')
  library('pacman')
}
pacman::p_load(magrittr, tidyverse, FactoMineR, factoextra, corrplot)

# ?magrittr
sessionInfo()

# -----------
### dados 
# -----------
# windows
#setwd('C:/dev/github/sipa-pca-2024/') 

# linux
setwd('~/developer/git.dqb2017/sipa-pca-2024/')
# dados padronizados (escore-Z)
#planilha <- read.csv('dados3.csv', sep=';', dec=',' , header = TRUE, stringsAsFactors=F)

# dados brutos (sem padronização)
planilha <- read.csv('dados.csv', sep=';', dec=',' , header = TRUE, stringsAsFactors=F)

# dados a partir do GitHub. 
# Devem estar separados por virgula.

#planilha2 <- read_csv("https://raw.githubusercontent.com/danielqbarbosa/sipa-pca-2024/main/dados.csv", col_name=T)
# ?read_csv
# -----------
# Tratamento: 
# -----------
# Lc: Lavoura controle
# L: Lavoura coinoculada
# LPc: Lavoura-Pecuária controle
# LP: Lavoura-Pecuária coinoculada
# LFc: Lavoura-Floresta controle
# LF: Lavoura-Floresta coinoculada
# LPFc: Lavoura-Pecuária-Floresta controle
# LPF: Lavoura-Pecuária-Floresta coinoculada
# 

#tabela <- planilha %>% select(-PROD)
tabela <- planilha 

head(planilha)
head(tabela)

### Distancia
# A funcao dist() calcula uma matriz de distancia de um quadro de dados de objetos por variaveis usando uma de suas m?tricas de dist?ncia embutidas (mais sobre isso abaixo).
# The dist() function calculates a distance matrix from a data frame of objects by variables using one of its inbuilt distance metrics (more on this below).
campo.distancia <- dist(tabela, method = "euclidean", diag=TRUE)

### Analise de PCO
# Escalonamento multidimensional classico (MDS) de uma matriz de dados. Tambem conhecida como analise de coordenadas principais (Gower, 1966).
#
# Classical multidimensional scaling (MDS) of a data matrix. Also known as principal coordinates analysis (Gower, 1966).
# The cmdscale() function then takes the distance matrix generated by dist() and performs a classical PCO. Then, as with nearly all multivariate methods, the output from the PCO needs to be examined in graph form to interpret the result of the analysis.

campo.pco <- cmdscale(campo.distancia, eig = TRUE, k = 7, x.ret = TRUE)

eig_num <- seq(1, length(campo.pco$eig), 1)
eig_num <- tabela$tratamento

barplot(campo.pco$eig, names.arg = eig_num, legend.text = TRUE, main = "Grafico de autovalor de PCO")


# -----------
# Model FactoMiner 
# -----------

#res_pca <- PCA(data.matrix(planilha) %>% select(-Arab), quali.sup = 1, graph = FALSE)
res_pca <- PCA(tabela, quali.sup = 1, graph = FALSE)
summary(res_pca)
sweep(res_pca$var$coord, 2, sqrt(res_pca$eig[1:ncol(res_pca$var$coord),1]), FUN = '/')

###### usando baseR 
data.matrix(tabela) %>% prcomp()
data.matrix(tabela) %>% princomp()

# -----------
### Grafico de correlacao das variaveis
# -----------
res_var <- get_pca_var(res_pca)
res_var

### Mapa de contribuição individual. 

corrplot(res_var$contrib, is.corr=FALSE)

# png("Figura X-Tabela de Contribuicao das variaveis.png")

### Mapa de contribuição - circular. 

fviz_pca_var(res_pca, col.var = "cos2", pointsize="cos2",  
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE )

### Mapa de contribuição - barras. 

figura <- fviz_contrib(res_pca, choice = "var", addlabels=T, axes=1) + 
  theme_minimal() 

png("Figura X-Contribuicao das variaveis para DIM-1.png")
print(figura)
dev.off()

figura <- fviz_contrib(res_pca, choice = "var", addlabels=T, axes=2) + 
  theme_minimal() 

png("Figura X-Contribuicao das variaveis para DIM-2.png")
print(figura)
dev.off()

?fviz_contrib

##############
# Analise PCA 
##############
figura <- fviz_pca_biplot(res_pca) 

png("Figura X-Analise PCA biplot.png")
print(figura)
dev.off()

# grafico melhorado 

Tratamento = tabela$tratamento

figura <- fviz_pca_biplot(res_pca, col.var = "blue", repel = TRUE) +
    geom_point(aes(shape=Tratamento, color=Tratamento), size=6) + 
    scale_shape_manual(values=c(15,0, 17,2, 16,1, 18,5))+
    theme_classic() +
    labs(title="Analise de Componentes Principais (PCA)", fill="Tratamentos")

png("Figura X-Analise PCA.png")
print(figura)
dev.off()

# Analise PCA - formato circular 

fviz_pca_var(res_pca, col.var = "blue")

fviz_pca_var(res_pca, col.var = "blue", geom.ind = "point", pointshape = 21, pointsize = 3 , fill.ind = tabela$tratamento)+
    theme_classic() +
    labs(title="Analise Multivariada", fill="Tratamentos",
    x="PCA1", y="PCA2")

fviz_pca_var(res_pca, col.var = "blue", geom.ind = "point", pointshape = 21, pointsize = 3 , fill.ind = tabela$tratamento)+
  theme() +
  labs(title="Analise Multivariada", fill="Tratamentos")

